#!/bin/sh

# Allow to switch proxy/noproxy  depending on condition
# (In this case IP changed)
#
# To use this
# create the following symbolic links
# ```
# sudo ln -s $(pwd)/999-proxy /etc/network/if-up.d/999-proxy
# sudo ln -s $(pwd)/999-proxy /etc/network/if-down.d/999-proxy
# ```

YOUR_CORPORATE_IP=172.28.9.21

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

logger -t if-up/proxy "Checking $IFACE for byebyeproxy"
# Check "ip link show $IFACE" and avoid local or bridge
if [ $IFACE != "wlp2s0" -a $IFACE != "enp0s31f6" ]
then
  logger -t if-up/proxy "$IFACE not concerned by byebyeproxy"
  exit 0
fi
ip address show $IFACE | grep -q "inet ${YOUR_CORPORATE_IP}"
if [ $? = 0 ]
then
  logger -t if-up/proxy "Enable byebyeproxy for $IFACE"
  ${DIR}/on.sh
else
  logger -t if-up/proxy "Disable byebyeproxy for $IFACE"
  ${DIR}/off.sh
fi
